
  
  window.webSnake = {};

  window.webSnake.urlMap = [
  {
    "oldUrl": "https://www.google.com/xjs/_/js/k=xjs.s.en_GB.U73jrqAs-ok.2019.O/ck=xjs.s._IGKMDzcXe4.L.B1.O/am=AAAIAAAgEAAAAAAAAAAAAAgAgBAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAQAAAAAAAAAAAAAAgAUAAAoEECQsgUAAAAAAOgFAgBSAAAAAAAAAPAAGAhBBAAAAAAAACICBBAAQAIAAAAAAAAAAAAAAAAAAIAAAABAAAAAABgAAQAAAYQKAAAAhQIAEAAAAAAAAAAAAAIgBAAAAIAESADw3_7QAQMAAAAIAAAAAQgEAIAAAAAQAAAGkjBgAAAAADJigQCAoDAAAAEIAQQACCAAAEQABCAAAAAAEAAAGAAAAEAAAAADYUEgCIBABRAACDgAAAAAAAAgAAAAAAAAEAQAQEAAAgAAAAAIAIBAAADIAwAAIEAABCAgAPAGCAwAAACJAAARAAAIBDAAQAAAAAAAgAAS-AEAgAAAAAAAnAAAQAgAIAGwiCIBAEAAAAAAQA4AjwdgSEEBAAAAAAAAAAAAAAAAAAAAAAEoCOZA-gUBBAAAAAAAAAAAAAAAAAAAAAAAAJAibGKtAQAB/d=0/dg=0/br=1/ujg=1/rs=ACT90oECrsxvL3hHjWxhgM4FbnWBtrY-rQ/m=syia,aLUfP,wQlYve,sy9ju,sy2vo,sy36k,sy9jt,sy9js,sy7rb,sy1t0,sy84,sy1t1,sy1s3,sy1ru,sy1rl,sy1s4,sy1ar,pKhWu,sy1rn,n7qy6d,sy1rp,HPGtmd,sy1rs,sy1rt,sy1rq,syp5,syll,syli,sylh,sykz,syky,sy1q7,uLYJpc,pHXghd?xjs=s3",
    "newUrl": "snake.js"
  }
];
  
  window.webSnake.blockedUrls = [
  "https://www.google.com/async/bgasy?ei=HxYRacOGJ7q5hbIPuofrkA0&opi=89978449&yv=3&cs=0&async=_fmt:jspb",
  "https://www.google.com/xjs/_/js/k=xjs.s.en_GB.U73jrqAs-ok.2019.O/am=AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAgAUAAAoEAAQAAAAAAAAAEAAAgACAAAAAAAAAAAAAAAAAAAAAAAAAAICABAAQAIAAAAAAAAAAAAAAAAAAIAAAAAAAAAAABgAAQAAAQQKAAAABQAAAAAAAAAAAAAAAAIgAAAAAIAESADw3_7QAQAAAAAAAAAAAQAAAAAAAAAAAAAAEgBgAAAAAABgAQCAoDAAAAEIAQQAAAAAAAAAAAAAAAAAEAAAAAAAAEAAAAAAAUAAAAAABQAACAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAIAAAADAAQAAAEAAAAAAAAAAAAAAAAAAAAAAAAAABDAAAAAAAAAAAAAC-AEAgAAAAAAAHAAAQAgAAACwgCIBAEAAAAAAQA4AjwdgSEEBAAAAAAAAAAAAAAAAAAAAAAEoCOZA-gEBBAAAAAAAAAAAAAAAAAAAAAAAAJAibGKtAQAB/d=0/dg=0/br=1/rs=ACT90oEgIap3HxSJewYtsZerM93WkA0APg/m=sb_wiz,aa,abd,sy1sb,sy16h,sy16b,sy160,sy166,sy16x,async,sy1uh,bgd,sy9fh,foot,sy3i6,kyn,sy1jj,sy1jk,lli,sy3hm,sy3hn,sy6h2,sonic,sy6rx,syhk,sy58r,sy3as,sy2b5,sy2b4,sy1cg,sy1cf,sy1ce,sy1cd,sy1ch,sy4n8,sy4n9,sy1cn,sy1cb,syax,sya0,sy9z,sy9y,sy9x,spch,tl,NdLnDf,QKZgZd,zD2Asd,sy1re,sy1rf,Qj0suc,JXS8fb,sy1sa,sy1gs,sy1s9,sy1s5,sy1rx,sy1gt,sy1s7,sy1s0,syeo,syc7,sy1ry,sy1s2,syel,sy1rz,sy1rk,Wct42,sy1sy,syq4,syor,sy1q4,sy1q3,syoh,sy1q2,syoj,sylv,sylu,syl6,sykc,sy1q1,sy1pz,sy1py,sy1px,sy1pv,sy1pu,sy1pt,sy1ps,sy1pr,sy1pq,LiBxPe?xjs=s4"
];
  
  